name: CICD pipeline

on:
  workflow_dispatch:
  push:
    branches: [ manualTrigger ]
  pull_request:
    branches: [ manualTrigger ]
env:
  SONAR_TOKEN: '75621cba6337eff300a0b42e8d68eb9d4cdbe709'
  SONAR_HOST_URL: 'http://brillioonesonar.eastus.cloudapp.azure.com:9000'
  
jobs:
  build:
    runs-on: 
      - self-hosted
      - label-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
        
      - name: Build with Maven
        run: mvn clean package
        
      - name: Run Tests
        run: mvn test
      
      - name: Publish Build Artifacts
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --destination gen-ai-javaspringboot --source ./ --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.2.0
        with:
          SONAR_TOKEN: ${{env.SONAR_TOKEN }}
          projectKey: ${{ env.sonar.projectKey }}
          projectName: ${{ env.sonar.projectName }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
          
      - name: Docker compose up
        run: docker-compose up -d
